name: Bug Report
description: Report a bug in nerf-edge-kit
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us fix it.
  
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - iOS/Vision Pro
        - iOS/iPhone
        - iOS/iPad
        - Web/Chrome
        - Web/Safari
        - Web/Firefox
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Initialize renderer with...
        2. Load NeRF model...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of nerf-edge-kit?
      placeholder: "1.0.0"
    validations:
      required: true