name: Feature Request
description: Suggest a new feature for nerf-edge-kit
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your needs.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Rendering Performance
        - New Platform Support
        - Developer Tools
        - API Enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
      placeholder: "A clear description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions?
      placeholder: "Other approaches you've considered."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else to add?
      placeholder: "Screenshots, mockups, links, etc."