name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details to help us understand your request.

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which platform should this feature target?
      options:
        - iOS/Vision Pro
        - iOS/iPhone
        - iOS/iPad
        - Web/TypeScript
        - Python/Training
        - All platforms
        - Not platform-specific
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Rendering Performance
        - New Platform Support
        - Developer Tools
        - API Enhancement
        - Documentation
        - Foveated Rendering
        - Neural Network Optimization
        - Streaming & Caching
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
      placeholder: "Add support for..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm trying to accomplish... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "The feature should..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: "I also considered..."

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: How would you and others use this feature?
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples