name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["feature-request", "needs-triage"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      options:
        - iOS/Vision Pro
        - Web/WebGPU
        - Python/Training
        - Cross-platform
    validations:
      required: true
EOF < /dev/null
