# Prometheus configuration for nerf-edge-kit monitoring
global:
  scrape_interval: 15s      # Default scrape interval
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'nerf-edge-kit'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/nerf_alerts.yml"
  - "rules/performance_alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NeRF Edge Kit web application
  - job_name: 'nerf-web'
    static_configs:
      - targets: ['nerf-web:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # NeRF Python API
  - job_name: 'nerf-api'
    static_configs:
      - targets: ['nerf-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scheme: http

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # GPU metrics (NVIDIA DCGM)
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s
    honor_labels: true

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Custom application metrics endpoints
  - job_name: 'nerf-performance'
    static_configs:
      - targets: ['nerf-web:3000', 'nerf-api:8000']
    metrics_path: '/metrics/performance'
    scrape_interval: 5s  # High frequency for performance metrics
    params:
      module: ['performance']

  # Health check monitoring
  - job_name: 'nerf-health'
    static_configs:
      - targets: ['nerf-web:3000', 'nerf-api:8000']
    metrics_path: '/health/metrics'
    scrape_interval: 30s

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200
    basic_auth:
      username: "nerf-edge-kit"
      password_file: "/etc/prometheus/remote_write_password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true